.TH FMAD 1 "2025/2/22" "FMAD Manual"

.SH NAME
fmad \- Calculate the derivative of a given equation.

.SH SYNOPSIS
fmad <equation>

.SH DESCRIPTION
The fmad program takes in a simple mathematical equation and calculates the derivative of the equation.

.SH EXAMPLES
.B
fmad "5x+4"

.B
fmad "2x^2+4x-3"

.B
fmad "5x^3+3x"

.SH EXIT STATUS
0 for success; 1 for error.

.SH AUTHOR
Written by Badger Code.